feat: time app finished
Xrazik1/rack_time_application pull request #1
Opened 2020-01-19 20:38 UTC by Xrazik1

2020-01-19 21:43 UTC, BubuntuClu commented on app.rb
>    def call(env)
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2020-01-19 21:51 UTC, Xrazik1 commented on app.rb
>    def call(env)
Доходит, о чём говорилось в чистой архитектуре))

2020-01-20 19:41 UTC, BubuntuClu requested changes

2020-01-20 19:41 UTC, BubuntuClu commented on app.rb
> +
```
formatter = TimeFormatter.new(params)
formatter.call

if formatter.valid_format?
  response(200, formatter.time_by_format)
else
  response(400, "Unknown time format #{formatter.unknown_format})


def response(status, body)
  response = Rack::Response.new
 ...
end
```

2020-01-20 19:41 UTC, BubuntuClu commented on app.rb
> +    @response_body = ["Unknown time format #{params}\n"]
в этом массиве могут быть и валидные форматы, так выводить будет не корректно

2020-01-20 19:41 UTC, BubuntuClu commented on time_formatter.rb
> +  VALID_TIME_KEYS = %w[year month day hour minute second].freeze
это лучше сделать хэшем, в качестве значений использовать структуру для strftime

2020-01-20 19:41 UTC, BubuntuClu commented on time_formatter.rb
> +      if %w[day month].include? time
не очень хороший цикл. в нем лучше по хэшу искать и составлять strtime строку. в этом цикле собираешь два массива, валидных и не валидных форматов.
и потом если невалидный массив не пустой выводить ошибку иначе по валидному формату составить строку через strftime

2020-01-20 19:41 UTC, BubuntuClu commented on time_formatter.rb
> +  def self.valid_format?(keys)
лучше будет создать метод инициализации, который начальные значения задаст и потом метод call для парсинга

2020-01-20 19:41 UTC, BubuntuClu commented on app.rb
> +      @response_code = 200
хорошо будет сделать метод для ответа

2020-01-22 18:48 UTC, merged